version: "3.8"

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: prime-jellyfin
    hostname: prime-jellyfin
    restart: unless-stopped

    # NVIDIA no Docker Desktop + WSL2
    gpus: all

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Bahia
      - UMASK=022
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility

    ports:
      - "8096:8096"

    volumes:
      - jellyfin_config:/config
      - jellyfin_cache:/cache

      # Sua m√≠dia do Windows (E:\Media) montada como /media/in
      - "E:/Media:/media/in:ro"

volumes:
  jellyfin_config:
  jellyfin_cache:


